// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohudeiqhtyzfybkdlrze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9odWRlaXFodHl6Znlia2RscnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDAxNDQsImV4cCI6MjA1OTk3NjE0NH0.234IfcRq99iaEh4L0f2mJEG-0mMQKuQFVVniwlT0yac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);